### ISSUE TITLE
[프론트백엔드 연결] 달리는 거리+칼로리 API 연결 및 테스트

### ISSUE THREAD

**Issue by coringcoring** [HCI-SVR/SVR#17]

**Comment by osjkate** [comment]
나이 입력받기
최대 심박수 = 220 - 나이

1. 강도 1 (빠르게 걷기)
100m 64초
가벼운 운동 50 ~ 60%
5초에 7.81m


2. 강도 2 (조깅)
100m 45초
다이어트 60 ~ 75%
5초에 11.1m


3. 강도 3 (러닝)
100m 30초
지구력과 근지구력 75 ~ 80%
5초에 16.65m
